server:
  port: 8082
  
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/EmployeeForum
#    password: password
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    
#    database-platform: org.hibernate.dialect.MySQLDialect
#  application:
#    name: EMPLOYEE-FORUM

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 215MB
  application:
    name: EMPLOYEE-FORUM

  datasource:
    url: jdbc:h2:file:./p3data;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE     
#url: jdbc:h2:file:./p3data

    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
    
    
    # alternative datasource: external mysql database example
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root

  jpa:
    # remove the next line, if you use mysql:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      