
server:  
 port:  8090
 
 
spring:  
  application:
    name: jenkins
    
eureka: 
  client:  
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultlZone: http://localhost:8761/eureka
  instance:
     hostname: localhost